[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spyeeg"
version = "0.1.0"
description = "Package for modelling electrophysiological responses to stimuli"
authors = [{name = "Pierre Hieu Guilleminot", email = "pierre.hieu.guilleminot@gmail.com"}, {name = "Mikolaj Kegler", email = "mikolajkegler@gmail.com"}, {name = "Michael Thornton", email = "m.thornton20@imperial.ac.uk"}]
license = {text = 'BSD 3'}
requires-python = ">3.8"
readme = "README.md"

[tool.setuptools]
packages = ["spyeeg"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
Repository = "https://github.com/phg17/sPyEEG"